services:
  db:
    image: postgres:15
    container_name: signature_db
    restart: always
    environment:
      POSTGRES_DB: signature
      POSTGRES_USER: signature_user
      POSTGRES_PASSWORD: signature_pass
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: signature_api
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=signature
      - DB_USER=signature_user
      - DB_PASS=signature_pass
    ports:
      - "5000:5000"

  gateway:
    build: ./gateway
    container_name: signature_gateway
    depends_on:
      - api
    ports:
      - "2525:25"
    networks:
      - default

volumes:
  db_data:
